### PR TITLE
authored the launch simulation function as well as functions for getting and sending worker messages

### PR DESCRIPTION
**Pull request by coder-guy22296**

### CODE REVIEW

**Review by stockle — APPROVED** [review]
Good

**Review by stockle — APPROVED** [review]
We should discuss parameters as a group, tomorrow or Monday night

**Review by stockle — APPROVED** [review]
Good

**Review by stockle — APPROVED** [review]
Prototypes look good

**Review by stockle — APPROVED** [review]
Good

**Review by seanwessmith — COMMENTED** [review]
code approved

**Pull request merged**
